// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';
import {structs} from '../models';
import {apple} from '../models';
import {splice} from '../models';
import {youtube} from '../models';

export function CancelDownload():Promise<void>;

export function CheckDependencies():Promise<Array<engine.DependencyStatus>>;

export function DetectURLType(arg1:string):Promise<string>;

export function GetAppDataDir():Promise<string>;

export function GetConfigPath():Promise<string>;

export function GetLogPath():Promise<string>;

export function GetSettings():Promise<structs.ConfigSet>;

export function GetWizardComplete():Promise<boolean>;

export function IsDownloading():Promise<boolean>;

export function LogFrontendError(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenLogFile():Promise<void>;

export function PickFolder():Promise<string>;

export function PreviewURL(arg1:string):Promise<apple.PreviewResult>;

export function SaveSettings(arg1:structs.ConfigSet):Promise<void>;

export function Search(arg1:string,arg2:string,arg3:number):Promise<{[key: string]: any}>;

export function SetWizardComplete(arg1:boolean):Promise<void>;

export function SpliceCancelExport():Promise<void>;

export function SpliceComputeTimings(arg1:splice.Project):Promise<Array<any>>;

export function SpliceDistributeDrift(arg1:splice.Project):Promise<splice.Project>;

export function SpliceGetPeaks(arg1:string,arg2:number):Promise<splice.WaveformPeaks>;

export function SpliceIsExporting():Promise<boolean>;

export function SpliceLoadProject(arg1:string):Promise<splice.Project>;

export function SpliceMasterAudioURL(arg1:string):Promise<string>;

export function SplicePickArtwork():Promise<string>;

export function SplicePickMasterFile():Promise<string>;

export function SplicePickOutputDir():Promise<string>;

export function SpliceProbeMaster(arg1:string):Promise<splice.MasterProbe>;

export function SpliceSaveProject(arg1:splice.Project):Promise<string>;

export function SpliceSetBoundary(arg1:splice.Project,arg2:number,arg3:number):Promise<splice.Project>;

export function SpliceSetTrackDuration(arg1:splice.Project,arg2:number,arg3:number):Promise<splice.Project>;

export function SpliceSetTrackStart(arg1:splice.Project,arg2:number,arg3:number):Promise<splice.Project>;

export function SpliceStartExport(arg1:splice.Project):Promise<void>;

export function StartDownload(arg1:Array<string>,arg2:string,arg3:boolean,arg4:boolean,arg5:boolean):Promise<void>;

export function StartDownloadJob(arg1:string,arg2:string,arg3:Array<number>,arg4:Array<string>,arg5:boolean,arg6:Array<youtube.DownloadMeta>):Promise<void>;
