// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function DetectURLType(arg1) {
  return window['go']['main']['App']['DetectURLType'](arg1);
}

export function GetAppDataDir() {
  return window['go']['main']['App']['GetAppDataDir']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetWizardComplete() {
  return window['go']['main']['App']['GetWizardComplete']();
}

export function IsDownloading() {
  return window['go']['main']['App']['IsDownloading']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenLogFile() {
  return window['go']['main']['App']['OpenLogFile']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PreviewURL(arg1) {
  return window['go']['main']['App']['PreviewURL'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Search(arg1, arg2, arg3) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3);
}

export function SetWizardComplete(arg1) {
  return window['go']['main']['App']['SetWizardComplete'](arg1);
}

export function StartDownload(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2, arg3, arg4, arg5);
}

export function StartDownloadJob(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartDownloadJob'](arg1, arg2, arg3, arg4);
}
