// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';
import {youtube} from '../models';
import {apple} from '../models';
import {media} from '../models';
import {structs} from '../models';
import {splice} from '../models';
import {main} from '../models';

export function CancelDownload():Promise<void>;

export function CheckDependencies():Promise<Array<engine.DependencyStatus>>;

export function CheckTrackDuplicates(arg1:string,arg2:string,arg3:Array<number>,arg4:string,arg5:string,arg6:Array<youtube.DownloadMeta>,arg7:apple.PreviewResult):Promise<engine.DuplicateCheckResult>;

export function ClearAllSyncCaches():Promise<media.CacheClearResult>;

export function ClearAppTempCache():Promise<media.CacheClearResult>;

export function ClearAppleMusicArtworkCache():Promise<media.CacheClearResult>;

export function DetectURLType(arg1:string):Promise<string>;

export function GetAppDataDir():Promise<string>;

export function GetAppleMusicCacheInfo():Promise<media.AppleMusicCacheInfo>;

export function GetConfigPath():Promise<string>;

export function GetLogPath():Promise<string>;

export function GetPlatform():Promise<string>;

export function GetRecentFiles():Promise<Array<string>>;

export function GetSettings():Promise<structs.ConfigSet>;

export function GetSetupComplete():Promise<boolean>;

export function GetSyncRepairPreparePreview():Promise<media.SyncRepairPreparePreview>;

export function GetWizardComplete():Promise<boolean>;

export function IsAppleMusicRunning():Promise<boolean>;

export function IsDownloading():Promise<boolean>;

export function LogFrontendError(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenApplePurgeLog():Promise<void>;

export function OpenConfigFolder():Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenLogFile():Promise<void>;

export function OpenSyncRepairLog():Promise<void>;

export function PickFolder():Promise<string>;

export function PreflightDownloadJob(arg1:string,arg2:string,arg3:string,arg4:string):Promise<engine.PreflightResult>;

export function PrepareAlbumForSync(arg1:string):Promise<media.AlbumPrepareResult>;

export function PrepareLibraryForSync():Promise<Array<media.AlbumPrepareResult>>;

export function PreviewPrepareAlbumForSync(arg1:string):Promise<media.AlbumPreparePreview>;

export function PreviewURL(arg1:string):Promise<apple.PreviewResult>;

export function RevealInFolder(arg1:string):Promise<void>;

export function RunAppleMusicDeepPurge(arg1:boolean):Promise<media.ApplePurgeResult>;

export function RunSyncRepair(arg1:media.SyncRepairOptions):Promise<media.SyncRepairResult>;

export function RunSyncRepairElevated():Promise<media.SyncRepairResult>;

export function SaveSettings(arg1:structs.ConfigSet):Promise<void>;

export function Search(arg1:string,arg2:string,arg3:number):Promise<{[key: string]: any}>;

export function SetSetupComplete(arg1:boolean):Promise<void>;

export function SetWizardComplete(arg1:boolean):Promise<void>;

export function SpliceCancelExport():Promise<void>;

export function SpliceComputeTimings(arg1:splice.Project):Promise<Array<any>>;

export function SpliceDistributeDrift(arg1:splice.Project):Promise<splice.Project>;

export function SpliceGetPeaks(arg1:string,arg2:number):Promise<splice.WaveformPeaks>;

export function SpliceIsExporting():Promise<boolean>;

export function SpliceLoadProject(arg1:string):Promise<splice.Project>;

export function SpliceMasterAudioURL(arg1:string):Promise<string>;

export function SplicePickArtwork():Promise<string>;

export function SplicePickMasterFile():Promise<string>;

export function SplicePickOutputDir():Promise<string>;

export function SpliceProbeMaster(arg1:string):Promise<splice.MasterProbe>;

export function SpliceSaveProject(arg1:splice.Project):Promise<string>;

export function SpliceSetBoundary(arg1:splice.Project,arg2:number,arg3:number):Promise<splice.Project>;

export function SpliceSetTrackDuration(arg1:splice.Project,arg2:number,arg3:number):Promise<splice.Project>;

export function SpliceSetTrackStart(arg1:splice.Project,arg2:number,arg3:number):Promise<splice.Project>;

export function SpliceStartExport(arg1:splice.Project):Promise<void>;

export function StartBulkDownloadJob(arg1:Array<engine.BulkQueueEntry>,arg2:string):Promise<void>;

export function StartDownload(arg1:Array<string>,arg2:string,arg3:boolean,arg4:boolean,arg5:boolean):Promise<void>;

export function StartDownloadJob(arg1:string,arg2:string,arg3:Array<number>,arg4:Array<string>,arg5:string,arg6:Array<youtube.DownloadMeta>):Promise<void>;

export function TagAnalyzeArtwork(arg1:string):Promise<media.ArtworkAccentAnalysis>;

export function TagAnalyzeArtworkSource(arg1:string,arg2:string):Promise<media.ArtworkAccentAnalysis>;

export function TagAnalyzeEmbeddedArtwork(arg1:string):Promise<media.ArtworkAccentAnalysis>;

export function TagApplyOptimizedArtwork(arg1:string,arg2:string):Promise<media.PreparedArtworkResult>;

export function TagFindAlbumCover(arg1:string):Promise<string>;

export function TagLocalFileURL(arg1:string):Promise<string>;

export function TagPickArtworkFile():Promise<string>;

export function TagPickAudioFile():Promise<string>;

export function TagPickSaveMediaFile(arg1:string):Promise<string>;

export function TagPreviewOptimizedArtwork(arg1:string):Promise<media.ArtworkAccentAnalysis>;

export function TagReadAlbumFolder(arg1:string):Promise<media.AlbumFolderReadResult>;

export function TagReadFile(arg1:string):Promise<media.AudioTagInfo>;

export function TagResolveDrop(arg1:Array<string>):Promise<main.TagDropResolve>;

export function TagWriteAlbumBatch(arg1:media.TagAlbumBatchInput):Promise<media.TagAlbumBatchResult>;

export function TagWriteFile(arg1:media.WriteAudioTagsInput):Promise<media.AudioTagInfo>;

export function ValidateIPhoneSync(arg1:string):Promise<media.SyncValidationResult>;

export function ValidateIPhoneSyncFolder(arg1:string):Promise<media.FolderSyncValidationResult>;
