// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function CheckTrackDuplicates(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CheckTrackDuplicates'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ClearAllSyncCaches() {
  return window['go']['main']['App']['ClearAllSyncCaches']();
}

export function ClearAppTempCache() {
  return window['go']['main']['App']['ClearAppTempCache']();
}

export function ClearAppleMusicArtworkCache() {
  return window['go']['main']['App']['ClearAppleMusicArtworkCache']();
}

export function DetectURLType(arg1) {
  return window['go']['main']['App']['DetectURLType'](arg1);
}

export function GetAppDataDir() {
  return window['go']['main']['App']['GetAppDataDir']();
}

export function GetAppleMusicCacheInfo() {
  return window['go']['main']['App']['GetAppleMusicCacheInfo']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSetupComplete() {
  return window['go']['main']['App']['GetSetupComplete']();
}

export function GetSyncRepairPreparePreview() {
  return window['go']['main']['App']['GetSyncRepairPreparePreview']();
}

export function GetWizardComplete() {
  return window['go']['main']['App']['GetWizardComplete']();
}

export function IsAppleMusicRunning() {
  return window['go']['main']['App']['IsAppleMusicRunning']();
}

export function IsDownloading() {
  return window['go']['main']['App']['IsDownloading']();
}

export function LogFrontendError(arg1, arg2, arg3) {
  return window['go']['main']['App']['LogFrontendError'](arg1, arg2, arg3);
}

export function OpenApplePurgeLog() {
  return window['go']['main']['App']['OpenApplePurgeLog']();
}

export function OpenConfigFolder() {
  return window['go']['main']['App']['OpenConfigFolder']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenLogFile() {
  return window['go']['main']['App']['OpenLogFile']();
}

export function OpenSyncRepairLog() {
  return window['go']['main']['App']['OpenSyncRepairLog']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PreflightDownloadJob(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PreflightDownloadJob'](arg1, arg2, arg3, arg4);
}

export function PrepareAlbumForSync(arg1) {
  return window['go']['main']['App']['PrepareAlbumForSync'](arg1);
}

export function PrepareLibraryForSync() {
  return window['go']['main']['App']['PrepareLibraryForSync']();
}

export function PreviewPrepareAlbumForSync(arg1) {
  return window['go']['main']['App']['PreviewPrepareAlbumForSync'](arg1);
}

export function PreviewURL(arg1) {
  return window['go']['main']['App']['PreviewURL'](arg1);
}

export function RevealInFolder(arg1) {
  return window['go']['main']['App']['RevealInFolder'](arg1);
}

export function RunAppleMusicDeepPurge(arg1) {
  return window['go']['main']['App']['RunAppleMusicDeepPurge'](arg1);
}

export function RunSyncRepair(arg1) {
  return window['go']['main']['App']['RunSyncRepair'](arg1);
}

export function RunSyncRepairElevated() {
  return window['go']['main']['App']['RunSyncRepairElevated']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Search(arg1, arg2, arg3) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3);
}

export function SetSetupComplete(arg1) {
  return window['go']['main']['App']['SetSetupComplete'](arg1);
}

export function SetWizardComplete(arg1) {
  return window['go']['main']['App']['SetWizardComplete'](arg1);
}

export function SpliceCancelExport() {
  return window['go']['main']['App']['SpliceCancelExport']();
}

export function SpliceComputeTimings(arg1) {
  return window['go']['main']['App']['SpliceComputeTimings'](arg1);
}

export function SpliceDistributeDrift(arg1) {
  return window['go']['main']['App']['SpliceDistributeDrift'](arg1);
}

export function SpliceGetPeaks(arg1, arg2) {
  return window['go']['main']['App']['SpliceGetPeaks'](arg1, arg2);
}

export function SpliceIsExporting() {
  return window['go']['main']['App']['SpliceIsExporting']();
}

export function SpliceLoadProject(arg1) {
  return window['go']['main']['App']['SpliceLoadProject'](arg1);
}

export function SpliceMasterAudioURL(arg1) {
  return window['go']['main']['App']['SpliceMasterAudioURL'](arg1);
}

export function SplicePickArtwork() {
  return window['go']['main']['App']['SplicePickArtwork']();
}

export function SplicePickMasterFile() {
  return window['go']['main']['App']['SplicePickMasterFile']();
}

export function SplicePickOutputDir() {
  return window['go']['main']['App']['SplicePickOutputDir']();
}

export function SpliceProbeMaster(arg1) {
  return window['go']['main']['App']['SpliceProbeMaster'](arg1);
}

export function SpliceSaveProject(arg1) {
  return window['go']['main']['App']['SpliceSaveProject'](arg1);
}

export function SpliceSetBoundary(arg1, arg2, arg3) {
  return window['go']['main']['App']['SpliceSetBoundary'](arg1, arg2, arg3);
}

export function SpliceSetTrackDuration(arg1, arg2, arg3) {
  return window['go']['main']['App']['SpliceSetTrackDuration'](arg1, arg2, arg3);
}

export function SpliceSetTrackStart(arg1, arg2, arg3) {
  return window['go']['main']['App']['SpliceSetTrackStart'](arg1, arg2, arg3);
}

export function SpliceStartExport(arg1) {
  return window['go']['main']['App']['SpliceStartExport'](arg1);
}

export function StartBulkDownloadJob(arg1, arg2) {
  return window['go']['main']['App']['StartBulkDownloadJob'](arg1, arg2);
}

export function StartDownload(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2, arg3, arg4, arg5);
}

export function StartDownloadJob(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StartDownloadJob'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function TagAnalyzeArtwork(arg1) {
  return window['go']['main']['App']['TagAnalyzeArtwork'](arg1);
}

export function TagAnalyzeEmbeddedArtwork(arg1) {
  return window['go']['main']['App']['TagAnalyzeEmbeddedArtwork'](arg1);
}

export function TagFindAlbumCover(arg1) {
  return window['go']['main']['App']['TagFindAlbumCover'](arg1);
}

export function TagLocalFileURL(arg1) {
  return window['go']['main']['App']['TagLocalFileURL'](arg1);
}

export function TagPickArtworkFile() {
  return window['go']['main']['App']['TagPickArtworkFile']();
}

export function TagPickAudioFile() {
  return window['go']['main']['App']['TagPickAudioFile']();
}

export function TagPickSaveMediaFile(arg1) {
  return window['go']['main']['App']['TagPickSaveMediaFile'](arg1);
}

export function TagPreviewOptimizedArtwork(arg1) {
  return window['go']['main']['App']['TagPreviewOptimizedArtwork'](arg1);
}

export function TagReadAlbumFolder(arg1) {
  return window['go']['main']['App']['TagReadAlbumFolder'](arg1);
}

export function TagReadFile(arg1) {
  return window['go']['main']['App']['TagReadFile'](arg1);
}

export function TagResolveDrop(arg1) {
  return window['go']['main']['App']['TagResolveDrop'](arg1);
}

export function TagWriteAlbumBatch(arg1) {
  return window['go']['main']['App']['TagWriteAlbumBatch'](arg1);
}

export function TagWriteFile(arg1) {
  return window['go']['main']['App']['TagWriteFile'](arg1);
}

export function ValidateIPhoneSync(arg1) {
  return window['go']['main']['App']['ValidateIPhoneSync'](arg1);
}

export function ValidateIPhoneSyncFolder(arg1) {
  return window['go']['main']['App']['ValidateIPhoneSyncFolder'](arg1);
}
