// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function DetectURLType(arg1) {
  return window['go']['main']['App']['DetectURLType'](arg1);
}

export function GetAppDataDir() {
  return window['go']['main']['App']['GetAppDataDir']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetWizardComplete() {
  return window['go']['main']['App']['GetWizardComplete']();
}

export function IsDownloading() {
  return window['go']['main']['App']['IsDownloading']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenLogFile() {
  return window['go']['main']['App']['OpenLogFile']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PreviewURL(arg1) {
  return window['go']['main']['App']['PreviewURL'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Search(arg1, arg2, arg3) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3);
}

export function SetWizardComplete(arg1) {
  return window['go']['main']['App']['SetWizardComplete'](arg1);
}

export function SpliceCancelExport() {
  return window['go']['main']['App']['SpliceCancelExport']();
}

export function SpliceComputeTimings(arg1) {
  return window['go']['main']['App']['SpliceComputeTimings'](arg1);
}

export function SpliceDistributeDrift(arg1) {
  return window['go']['main']['App']['SpliceDistributeDrift'](arg1);
}

export function SpliceGetPeaks(arg1, arg2) {
  return window['go']['main']['App']['SpliceGetPeaks'](arg1, arg2);
}

export function SpliceIsExporting() {
  return window['go']['main']['App']['SpliceIsExporting']();
}

export function SpliceLoadProject(arg1) {
  return window['go']['main']['App']['SpliceLoadProject'](arg1);
}

export function SpliceMasterAudioURL(arg1) {
  return window['go']['main']['App']['SpliceMasterAudioURL'](arg1);
}

export function SplicePickArtwork() {
  return window['go']['main']['App']['SplicePickArtwork']();
}

export function SplicePickMasterFile() {
  return window['go']['main']['App']['SplicePickMasterFile']();
}

export function SplicePickOutputDir() {
  return window['go']['main']['App']['SplicePickOutputDir']();
}

export function SpliceProbeMaster(arg1) {
  return window['go']['main']['App']['SpliceProbeMaster'](arg1);
}

export function SpliceSaveProject(arg1) {
  return window['go']['main']['App']['SpliceSaveProject'](arg1);
}

export function SpliceSetBoundary(arg1, arg2, arg3) {
  return window['go']['main']['App']['SpliceSetBoundary'](arg1, arg2, arg3);
}

export function SpliceSetTrackDuration(arg1, arg2, arg3) {
  return window['go']['main']['App']['SpliceSetTrackDuration'](arg1, arg2, arg3);
}

export function SpliceSetTrackStart(arg1, arg2, arg3) {
  return window['go']['main']['App']['SpliceSetTrackStart'](arg1, arg2, arg3);
}

export function SpliceStartExport(arg1) {
  return window['go']['main']['App']['SpliceStartExport'](arg1);
}

export function StartDownload(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2, arg3, arg4, arg5);
}

export function StartDownloadJob(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StartDownloadJob'](arg1, arg2, arg3, arg4, arg5, arg6);
}
