// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';
import {structs} from '../models';

export function CancelDownload():Promise<void>;

export function CheckDependencies():Promise<Array<engine.DependencyStatus>>;

export function DetectURLType(arg1:string):Promise<string>;

export function GetAppDataDir():Promise<string>;

export function GetConfigPath():Promise<string>;

export function GetLogPath():Promise<string>;

export function GetSettings():Promise<structs.ConfigSet>;

export function GetWizardComplete():Promise<boolean>;

export function IsDownloading():Promise<boolean>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenLogFile():Promise<void>;

export function PickFolder():Promise<string>;

export function PreviewURL(arg1:string):Promise<engine.PreviewResult>;

export function SaveSettings(arg1:structs.ConfigSet):Promise<void>;

export function Search(arg1:string,arg2:string,arg3:number):Promise<{[key: string]: any}>;

export function SetWizardComplete(arg1:boolean):Promise<void>;

export function StartDownload(arg1:Array<string>,arg2:string,arg3:boolean,arg4:boolean,arg5:boolean):Promise<void>;

export function StartDownloadJob(arg1:string,arg2:string,arg3:Array<number>,arg4:Array<string>):Promise<void>;
